In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv("student_class1.csv")

In [4]:
data.head()

Roll No  S1  S2  S3  S4  S5  S6
0        1  95  77  77  73  43  93
1        2  89  96  65  78  99  74
2        3  65  62  88  91  45  75
3        4  78  42  78  64  69  54
4        5  81  68  93  65  84  54

In [30]:
X = data.loc[:,["S1","S2","S3","S4","S5"]]
y = data.loc[:,"S6"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)



### Training Our model...

In [31]:
# Linear Regresssion...
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(X_train,y_train)
pred1 = model1.predict(X_test)
print(pred1[0:5])


[68.47737919 74.82379459 71.21848636 74.79512477 72.941971  ]


In [32]:
# Gradient Boosting Regressor
from sklearn.ensemble import GradientBoostingRegressor
model2 = GradientBoostingRegressor()
model2.fit(X_train,y_train)
pred2 = model2.predict(X_test)
print(pred2[0:5])


[75.01273343 80.36807484 77.81186039 73.018835   84.99201319]


In [33]:
# Bayesian Ridge
from sklearn.linear_model import BayesianRidge
model3 = BayesianRidge()
model3.fit(X_train,y_train)
pred3 = model3.predict(X_test)
print(pred3[0:5])


[69.62552865 71.57912053 70.50579972 71.57225446 71.05411544]


In [37]:
# RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor
model4 = RandomForestRegressor()
model4.fit(X_train,y_train)
pred4 = model4.predict(X_test)
print(pred4[0:5])

[73.55 74.52 77.07 72.08 82.02]


## Checking Accuracy of Model's.. 

In [38]:
print("Acccuracy of Linear Regression:- ",model1.score(X_test,y_test))
print("Acccuracy of Gradient Boosting Regressor:- ",model2.score(X_test,y_test))
print("Acccuracy of Bayesian Ridge:- ",model3.score(X_test,y_test))
print("Acccuracy of Random Forest Regressor:- ",model4.score(X_test,y_test))

Acccuracy of Linear Regression:-  0.03197047680259557
Acccuracy of Gradient Boosting Regressor:-  -0.06063464254149653
Acccuracy of Bayesian Ridge:-  0.014542649212469172
Acccuracy of Random Forest Regressor:-  -0.010343603985157213


In [39]:
from sklearn.metrics import r2_score
ensemble_prediction = (pred1*0.3 + pred2*0.1 + pred3*0.3 + pred4*0.3)

r2_score_ensemble = r2_score(y_test,ensemble_prediction)
print("---Ensemble Model Accuracy---")
print(r2_score_ensemble)

---Ensemble Model Accuracy---
0.0324262011786548
